name: Semantic Release
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Add Status Comment
    steps:
      - name: Comment
        id: comment
        uses: adobe-rnd/github-semantic-release-comment-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
